"""Generated Markdown for backup plan and automation readiness."""

from __future__ import annotations

from music_rig.automation import CAPABILITIES, EFFECT_ADAPTER, AdapterFamily
from music_rig.models import BackupsDocument, PerformanceDocument, PerformanceEffectKind

BACKUPS_BANNER = (
    "<!-- GENERATED FROM data/backups.yaml BY `uv run rig render`. "
    "DO NOT EDIT THIS FILE DIRECTLY. -->"
)
AUTOMATION_BANNER = (
    "<!-- GENERATED FROM automation registry + data/performance.yaml BY "
    "`uv run rig render`. DO NOT EDIT THIS FILE DIRECTLY. -->"
)


def _cell(value: object) -> str:
    return (
        str(value if value not in (None, "") else "—")
        .replace("|", "\\|")
        .replace("\n", " ")
    )


def render_backups_doc(doc: BackupsDocument) -> str:
    lines = [
        "# Backups",
        "",
        BACKUPS_BANNER,
        "",
        "Canonical backup / archive plan. Absolute paths belong only in gitignored "
        "`.rig.local.yaml`. Evidence remains INTENDED until restore/export is verified.",
        "",
        "## Items",
        "",
        "| ID | Label | Category | Kind | Importance | Locator | Evidence | TODOs |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for item in doc.items:
        lines.append(
            f"| {item.id} | {_cell(item.label)} | {item.category.value} | "
            f"{item.kind.value} | {item.importance.value} | "
            f"{_cell(item.locator_key)} | {item.evidence.value} | "
            f"{_cell(', '.join(item.related_todos))} |"
        )
    lines.extend(["", "## Instructions", ""])
    for item in doc.items:
        lines.append(f"### {item.label} (`{item.id}`)")
        lines.append("")
        if item.manual_instructions:
            lines.append(_cell(item.manual_instructions))
            lines.append("")
        if item.notes:
            lines.append(f"Notes: {_cell(item.notes)}")
            lines.append("")
    lines.extend(
        [
            "## Commands",
            "",
            "```bash",
            "uv run rig backup plan",
            "uv run rig backup status",
            "uv run rig snapshot create",
            "uv run rig backup create --output /path/to/archive",
            "```",
            "",
            "`rig snapshot create` captures canonical `data/*.yaml`. "
            "`rig backup create` embeds a snapshot and copies configured FILE_COPY / "
            "DIRECTORY_COPY items; MANUAL_EXPORT items are reported for operator action.",
            "",
            "Broad `--snapshot-before` integration on mutation commands is deferred; "
            "use `uv run rig snapshot create` manually before risky changes.",
            "",
        ]
    )
    return "\n".join(lines) + "\n"


def render_automation_readiness_doc(performance: PerformanceDocument) -> str:
    lines = [
        "# Automation readiness",
        "",
        AUTOMATION_BANNER,
        "",
        "Honest capability registry for Stage 11. No fake adapters: unimplemented "
        "families never report success.",
        "",
        "## Capabilities",
        "",
        "| Adapter | Status |",
        "|---|---|",
    ]
    for family in AdapterFamily:
        lines.append(f"| {family.value} | {CAPABILITIES[family].value} |")
    lines.extend(
        [
            "",
            "## Performance effect mapping",
            "",
            "| Effect kind | Adapter |",
            "|---|---|",
        ]
    )
    for kind in PerformanceEffectKind:
        adapter = EFFECT_ADAPTER[kind]
        lines.append(f"| {kind.value} | {adapter.value} |")
    lines.extend(
        [
            "",
            "## Safety",
            "",
            "- `rig performance simulate` prints "
            "`SIMULATION — NO EXTERNAL ACTIONS WILL BE EXECUTED` and never talks to "
            "OBS, Ableton, MIDI, Stream Deck, or macOS.",
            "- `rig performance preflight` is advisory and never gates `rig now --play`.",
            "- `rig performance plan` compiles effect order without executing.",
            "",
            "## Sample action plans",
            "",
            "| Action | Effects | Notes |",
            "|---|---:|---|",
        ]
    )
    for action in performance.actions[:12]:
        kinds = ", ".join(effect.kind.value for effect in action.effects) or "—"
        lines.append(
            f"| {action.id} | {len(action.effects)} | {_cell(kinds)} |"
        )
    lines.extend(
        [
            "",
            "## Commands",
            "",
            "```bash",
            "uv run rig automation capabilities",
            "uv run rig performance plan panic",
            "uv run rig performance simulate panic",
            "uv run rig performance preflight --mode pfl-jam",
            "```",
            "",
        ]
    )
    return "\n".join(lines) + "\n"
