"""Markdown projections for PFL performance and live recovery contracts."""

from __future__ import annotations

from music_rig.models import PerformanceDocument
from music_rig.performance_state import PerformanceReadiness

PERFORMANCE_BANNER = (
    "<!-- GENERATED FROM data/performance.yaml AND data/control-surfaces.yaml BY "
    "`uv run rig render`. DO NOT EDIT THIS FILE DIRECTLY. -->"
)
RECOVERY_BANNER = (
    "<!-- GENERATED FROM data/performance.yaml BY `uv run rig render`. "
    "DO NOT EDIT THIS FILE DIRECTLY. -->"
)


def _cell(value: object) -> str:
    return str(value if value not in (None, "") else "—").replace("|", "\\|").replace("\n", " ")


def render_performance_doc(
    doc: PerformanceDocument, surfaces, readiness: PerformanceReadiness
) -> str:
    lines = [
        "# Performance",
        "",
        PERFORMANCE_BANNER,
        "",
        "These are semantic performance contracts and design evidence, not live telemetry.",
        "",
        f"## Readiness: {readiness.result.value}",
        "",
        "Readiness is advisory. A PARTIAL result must not block `rig now --play`.",
        "",
    ]
    if readiness.reasons:
        for reason in readiness.reasons:
            lines.append(f"- {_cell(reason)}")
        lines.append("")
    lines.extend(
        [
            "## Modes",
            "",
            "| ID | Label | Purpose | Required actions | Optional actions | Evidence |",
            "|---|---|---|---|---|---|",
        ]
    )
    for mode in doc.modes:
        lines.append(
            f"| {mode.id} | {_cell(mode.label)} | {_cell(mode.purpose)} | "
            f"{_cell(', '.join(mode.required_actions))} | "
            f"{_cell(', '.join(mode.optional_actions))} | {mode.evidence.value} |"
        )
    lines.extend(
        [
            "",
            "## Actions",
            "",
            "| ID | Label | Category | Criticality | Effects | Evidence | Notes |",
            "|---|---|---|---|---:|---|---|",
        ]
    )
    for action in doc.actions:
        lines.append(
            f"| {action.id} | {_cell(action.label)} | {action.category.value} | "
            f"{action.criticality.value} | {len(action.effects)} | "
            f"{action.evidence.value} | {_cell(action.notes)} |"
        )
    lines.extend(
        [
            "",
            "## Bindings",
            "",
            "| ID | Action | Source | Context | Control | Evidence | Notes |",
            "|---|---|---|---|---|---|---|",
        ]
    )
    for binding in doc.bindings:
        lines.append(
            f"| {binding.id} | {binding.action_ref} | "
            f"{binding.controller_ref or binding.surface_ref} | {binding.context_ref} | "
            f"{binding.control_ref} | {binding.evidence.value} | {_cell(binding.notes)} |"
        )
    lines.extend(
        [
            "",
            "## Non-MIDI control surfaces",
            "",
            "| Surface | Coverage | Contexts | Modeled controls | Evidence |",
            "|---|---|---:|---:|---|",
        ]
    )
    for surface in surfaces.surfaces:
        controls = [control for context in surface.contexts for control in context.controls]
        evidence = sorted(
            {context.evidence.value for context in surface.contexts}
            | {control.evidence.value for control in controls}
        )
        lines.append(
            f"| {surface.gear_ref} | {surface.coverage.value} | "
            f"{len(surface.contexts)} | {len(controls)} | {_cell(', '.join(evidence))} |"
        )
    lines.extend(
        [
            "",
            "## Requirements",
            "",
            "| ID | Description | Evidence | Related TODOs |",
            "|---|---|---|---|",
        ]
    )
    for requirement in doc.requirements:
        lines.append(
            f"| {requirement.id} | {_cell(requirement.description)} | "
            f"{requirement.evidence.value} | "
            f"{_cell(', '.join(requirement.related_todos))} |"
        )
    return "\n".join(lines) + "\n"


def render_live_recovery_doc(doc: PerformanceDocument) -> str:
    lines = [
        "# Live Recovery",
        "",
        RECOVERY_BANNER,
        "",
        "Recovery procedures remain evidence-labeled; INTENDED is not VERIFIED.",
        "",
        "| Scenario | Severity | Symptom | Actions | Keyboard/mouse | Evidence |",
        "|---|---|---|---|---|---|",
    ]
    for scenario in doc.recovery:
        lines.append(
            f"| {scenario.label} (`{scenario.id}`) | {scenario.severity.value} | "
            f"{_cell(scenario.symptom)} | {_cell(', '.join(scenario.action_refs))} | "
            f"{_cell(scenario.keyboard_mouse_required)} | {scenario.evidence.value} |"
        )
        if scenario.manual_steps:
            lines.extend(["", f"## {scenario.label}", ""])
            for step in scenario.manual_steps:
                lines.append(f"- {_cell(step)}")
    return "\n".join(lines) + "\n"
