flowchart LR
  subgraph CleanPaths[Clean capture paths]
    Acoustic --> AcPre[BOSS acoustic preamp] --> AcABY[A/B/Y] --> Tascam5[TASCAM 5]
    Bass --> BassPre[BBox preamp] --> BassABY[A/B/Y] --> Tascam6[TASCAM 6]
    Electric[Electric guitar] --> ElPre[Flamma preamp] --> ElABY[A/B/Y] --> Tascam7[TASCAM 7]
  end

  Bass --> Alesis1[Alesis Ch 1]
  Guitar[Guitar] --> Alesis2[Alesis Ch 2]
  Kazoo[Electric Kazoo] --> Alesis4[Alesis Ch 4]
  Privia --> Alesis56[Alesis Ch 5/6]
  MiniKORG --> Tascam34[TASCAM 3/4]
  SR18[Alesis SR-18] --> Tascam1112[TASCAM 11/12]

  Alesis1 --> Aux[AUX SEND]
  Alesis2 --> Aux
  Alesis4 --> Aux
  Alesis56 --> Aux

  Aux --> RC1[BOSS RC-1] --> CryBaby --> JOYO
  JOYO --> ChainA[DIRTY: OD/BD/JB/MT/DS]
  JOYO --> ChainB[SPACE: SY-1 + PH-3/TR-2 + LS-2 loops]
  ChainA --> CH1[BOSS CH-1 Stereo]
  ChainB --> CH1
  CH1 --> AlesisReturn[Alesis Stereo Return]

  AlesisMain[Alesis Main Out] --> Tascam12[TASCAM 1/2]
  AlesisMonitor[Alesis Monitor Out] --> KAOSS[KAOSS Replay] --> Tascam910[TASCAM 9/10]
