flowchart TB
  T1[TASCAM 1: Mixer L]
  T2[TASCAM 2: Mixer R]
  T3[TASCAM 3: miniKORG L]
  T4[TASCAM 4: miniKORG R]
  T5[TASCAM 5: Guitar Clean]
  T6[TASCAM 6: Open]
  T7[TASCAM 7: Bass Clean]
  T8[TASCAM 8: Open]
  T9[TASCAM 9: KAOSS L]
  T10[TASCAM 10: KAOSS R]
