flowchart TB
  T1[TASCAM 1: Mixer L]
  T2[TASCAM 2: Mixer R]
  T3[TASCAM 3: miniKORG L]
  T4[TASCAM 4: miniKORG R]
  T5[TASCAM 5: Acoustic Clean]
  T6[TASCAM 6: Bass Clean]
  T7[TASCAM 7: Electric Guitar Clean]
  T8[TASCAM 8: Unassigned]
  T9[TASCAM 9: KAOSS L]
  T10[TASCAM 10: KAOSS R]
  T11[TASCAM 11: SR-18 L]
  T12[TASCAM 12: SR-18 R]
  T13[TASCAM 13-16: Unassigned]
